return {
    {
        Name = "Air_Block",
        Rarity = "Air",
        RarityWeight = 4,
        Color = "#55AAFF",
        HitPower = 350,
    },
    {
        Name = "Basic_Block",
        Rarity = "Common",
        RarityWeight = 50,
        Color = "#F5CD30",
        HitPower = 6,
    },
    {
        Name = "Diamond_Block",
        Rarity = "Diamond",
        RarityWeight = 10,
        Color = "#A0EAFF",
        HitPower = 150,
    },
    {
        Name = "Epic_Block",
        Rarity = "Epic",
        RarityWeight = 6,
        Color = "#E27BFF",
        HitPower = 250,
    },
    {
        Name = "Galaxy_Block",
        Rarity = "Galaxy",
        RarityWeight = 3,
        Color = "#54A4B0",
        HitPower = 500,
    },
    {
        Name = "Gold_Block",
        Rarity = "Gold",
        RarityWeight = 15,
        Color = "#FFD900",
        HitPower = 800,
    },
    {
        Name = "Lava_Block",
        Rarity = "Lava",
        RarityWeight = 25,
        Color = "#FFC800",
        HitPower = 100,
    },
    {
        Name = "Legendary_Block",
        Rarity = "Legendary",
        RarityWeight = 2,
        Color = "#FF4759",
        HitPower = 1000,
    },
    {
        Name = "Rainbow_Block",
        Rarity = "Rainbow",
        RarityWeight = 2,
        Color = "#29F970",
        HitPower = 750,
    },
    {
        Name = "Rare_Block",
        Rarity = "Rare",
        RarityWeight = 25,
        Color = "#62BBFF",
        HitPower = 30,
    },
}