return {
	["Lirili Larila"] = {
		Rarity = 60000000,
		RarityType = "Common",
		CashPerSecond = 1,
		Type = "None",
        Timer = 30,
	},
	["Trippi Troppi"] = {
		Rarity = 50000000,
		RarityType = "Common",
		CashPerSecond = 2,
		Type = "Water",
        Timer = 30,
	},
	["Fluri Flura"] = {
		Rarity = 40000000,
		RarityType = "Common",
		CashPerSecond = 3,
		Type = "Air",
        Timer = 30,
	},
	["Pipi Kiwi"] = {
		Rarity = 30000000,
		RarityType = "Common",
		CashPerSecond = 4,
		Type = "None",
        Timer = 30,
	},
	["Svinina Bombardino"] = {
		Rarity = 20000000,
		RarityType = "Common",
		CashPerSecond = 6,
		Type = "None",
        Timer = 30,
	},
	["Brr Brr Patapim"] = {
		Rarity = 10000000,
		RarityType = "Common",
		CashPerSecond = 8,
		Type = "None",
        Timer = 30,
	},
	["Boneca Ambalabu"] = {
		Rarity = 9000000,
		RarityType = "Uncommon",
		CashPerSecond = 10,
		Type = "None",
        Timer = 30,
	},
	["Cacto Hipopotamo"] = {
		Rarity = 8000000,
		RarityType = "Uncommon",
		CashPerSecond = 12,
		Type = "Water",
        Timer = 30,
	},
	["Gangster Footera"] = {
		Rarity = 7000000,
		RarityType = "Uncommon",
		CashPerSecond = 14,
		Type = "None",
        Timer = 30,
	},
	["Chimpanzini Bananini"] = {
		Rarity = 6000000,
		RarityType = "Uncommon",
		CashPerSecond = 18,
		Type = "None",
        Timer = 30,
	},
	["Frigo Camelo"] = {
		Rarity = 5000000,
		RarityType = "Uncommon",
		CashPerSecond = 20,
		Type = "None",
        Timer = 30,
	},
	Garamararam = {
		Rarity = 4000000,
		RarityType = "Uncommon",
		CashPerSecond = 24,
		Type = "None",
        Timer = 30,
	},
	["Talpa Di Fero"] = {
		Rarity = 3500000,
		RarityType = "Uncommon",
		CashPerSecond = 26,
		Type = "None",
        Timer = 30,
	},
	["Ta Ta Ta Ta Sahur"] = {
		Rarity = 3000000,
		RarityType = "Rare",
		CashPerSecond = 28,
		Type = "None",
        Timer = 30,
	},
	["Tung Sahur"] = {
		Rarity = 2700000,
		RarityType = "Rare",
		CashPerSecond = 32,
		Type = "None",
        Timer = 30,
	},
	["Trippi Troppi Troppa Trippa"] = {
		Rarity = 2400000,
		RarityType = "Rare",
		CashPerSecond = 44,
		Type = "Water",
        Timer = 30,
	},
	["Bobrito Bandito"] = {
		Rarity = 2100000,
		RarityType = "Rare",
		CashPerSecond = 56,
		Type = "None",
        Timer = 30,
	},
	["Trulimero Trulicina"] = {
		Rarity = 1800000,
		RarityType = "Rare",
		CashPerSecond = 68,
		Type = "Water",
        Timer = 30,
	},
	Madudung = {
		Rarity = 1600000,
		RarityType = "Rare",
		CashPerSecond = 76,
		Type = "None",
        Timer = 30,
	},
	["Bananita Dolphinita"] = {
		Rarity = 1400000,
		RarityType = "Rare",
		CashPerSecond = 84,
		Type = "Water",
        Timer = 30,
	},
	["Rhino Toasterino"] = {
		Rarity = 900000,
		RarityType = "Epic",
		CashPerSecond = 96,
		Type = "None",
        Timer = 30,
	},
	["Orangutini Ananassini"] = {
		Rarity = 800000,
		RarityType = "Epic",
		CashPerSecond = 108,
		Type = "None",
        Timer = 30,
	},
	["Odin Din Din Dun"] = {
		Rarity = 700000,
		RarityType = "Epic",
		CashPerSecond = 120,
		Type = "None",
        Timer = 30,
	},
	["Cappuccino Assassino"] = {
		Rarity = 600000,
		RarityType = "Epic",
		CashPerSecond = 132,
		Type = "None",
        Timer = 30,
	},
	["Brri Brri Bicus Dicus"] = {
		Rarity = 500000,
		RarityType = "Epic",
		CashPerSecond = 144,
		Type = "Air",
        Timer = 30,
	},
	["Glorbo Fruttodrillo"] = {
		Rarity = 450000,
		RarityType = "Epic",
		CashPerSecond = 160,
		Type = "Water",
        Timer = 30,
	},
	["Bambini Crostini"] = {
		Rarity = 400000,
		RarityType = "Epic",
		CashPerSecond = 180,
		Type = "None",
        Timer = 30,
	},
	["Avocadini Guffo"] = {
		Rarity = 350000,
		RarityType = "Epic",
		CashPerSecond = 200,
		Type = "Air",
        Timer = 30,
	},
	["Quesadilla Crocodila"] = {
		Rarity = 330000,
		RarityType = "Epic",
		CashPerSecond = 225,
		Type = "None",
        Timer = 30,
	},
	["Six Seven"] = {
		Rarity = 300000,
		RarityType = "Legendary",
		CashPerSecond = 250,
		Type = "None",
        Timer = 30,
	},
	["Ballerina Cappuccina"] = {
		Rarity = 250000,
		RarityType = "Legendary",
		CashPerSecond = 320,
		Type = "None",
        Timer = 30,
	},
	["Chef Crabracadabra"] = {
		Rarity = 210000,
		RarityType = "Legendary",
		CashPerSecond = 480,
		Type = "Water",
        Timer = 30,
	},
	["Strawberrelli Flamingelli"] = {
		Rarity = 180000,
		RarityType = "Legendary",
		CashPerSecond = 640,
		Type = "Water",
        Timer = 30,
	},
	["Pandaccini Bananini"] = {
		Rarity = 150000,
		RarityType = "Legendary",
		CashPerSecond = 820,
		Type = "None",
        Timer = 30,
	},
	Matteo = {
		Rarity = 130000,
		RarityType = "Legendary",
		CashPerSecond = 950,
		Type = "None",
        Timer = 30,
	},
	["Burbaloni Luliloli"] = {
		Rarity = 110000,
		RarityType = "Legendary",
		CashPerSecond = 1040,
		Type = "None",
        Timer = 30,
	},
	["Pipi Potato"] = {
		Rarity = 90000,
		RarityType = "Legendary",
		CashPerSecond = 1100,
		Type = "None",
        Timer = 30,
	},
	["Blueberrinni Octopusini"] = {
		Rarity = 70000,
		RarityType = "Legendary",
		CashPerSecond = 1160,
		Type = "None",
        Timer = 30,
	},
	["Bombombini Gusini"] = {
		Rarity = 50000,
		RarityType = "Mythic",
		CashPerSecond = 1300,
		Type = "Air",
        Timer = 30,
	},
	["Bombardiro Crocodilo"] = {
		Rarity = 40000,
		RarityType = "Mythic",
		CashPerSecond = 1360,
		Type = "Air",
        Timer = 30,
	},
	["Cocofanto Elefanto"] = {
		Rarity = 32000,
		RarityType = "Mythic",
		CashPerSecond = 1520,
		Type = "None",
        Timer = 30,
	},
	["Girafa Celeste"] = {
		Rarity = 25000,
		RarityType = "Mythic",
		CashPerSecond = 1760,
		Type = "None",
        Timer = 30,
	},
	["Tralalero Tralala"] = {
		Rarity = 20000,
		RarityType = "Mythic",
		CashPerSecond = 2000,
		Type = "Water",
        Timer = 30,
	},
	["Orcalero Orcala"] = {
		Rarity = 15000,
		RarityType = "Mythic",
		CashPerSecond = 2240,
		Type = "Water",
        Timer = 30,
	},
	["Cavallo Virtuoso"] = {
		Rarity = 12000,
		RarityType = "Mythic",
		CashPerSecond = 2480,
		Type = "None",
        Timer = 30,
	},
	["Zibra Zubra Zibralini"] = {
		Rarity = 10000,
		RarityType = "Mythic",
		CashPerSecond = 2720,
		Type = "None",
        Timer = 30,
	},
	["Ballerino Lololo"] = {
		Rarity = 9000,
		RarityType = "Mythic",
		CashPerSecond = 3040,
		Type = "None",
        Timer = 30,
	},
	["Gorillo Watermelondrillo"] = {
		Rarity = 8000,
		RarityType = "Mythic",
		CashPerSecond = 3200,
		Type = "None",
        Timer = 30,
	},
	Lerulerulerule = {
		Rarity = 7000,
		RarityType = "Mythic",
		CashPerSecond = 3340,
		Type = "None",
        Timer = 30,
	},
	["La Vacca Saturno Saturnita"] = {
		Rarity = 5000,
		RarityType = "Secret",
		CashPerSecond = 3700,
		Type = "None",
        Timer = 30,
	},
	["Pot Hotspot"] = {
		Rarity = 4000,
		RarityType = "Secret",
		CashPerSecond = 3850,
		Type = "None",
        Timer = 30,
	},
	["Los Tralaleritos"] = {
		Rarity = 3000,
		RarityType = "Secret",
		CashPerSecond = 4160,
		Type = "Water",
        Timer = 30,
	},
	["Dragon Cannelloni"] = {
		Rarity = 2000,
		RarityType = "Secret",
		CashPerSecond = 4640,
		Type = "Air",
        Timer = 30,
	},
	["Esok Sekolah"] = {
		Rarity = 1500,
		RarityType = "Secret",
		CashPerSecond = 5040,
		Type = "None",
        Timer = 30,
	},
	["Job Job Job Sahur"] = {
		Rarity = 1000,
		RarityType = "Secret",
		CashPerSecond = 5520,
		Type = "None",
        Timer = 30,
	},
	["Strawberry Elephant"] = {
		Rarity = 800,
		RarityType = "Secret",
		CashPerSecond = 5920,
		Type = "None",
        Timer = 30,
	},
	["Agarrini La Pallini"] = {
		Rarity = 600,
		RarityType = "Secret",
		CashPerSecond = 6400,
		Type = "None",
        Timer = 30,
	},
	["Karkerkar Kurkur"] = {
		Rarity = 500,
		RarityType = "Secret",
		CashPerSecond = 6800,
		Type = "None",
        Timer = 30,
	},
	["Tralalita Tralala"] = {
		Rarity = 400,
		RarityType = "Secret",
		CashPerSecond = 7200,
		Type = "Water",
        Timer = 30,
	},
	["Torrtuginni Dragonfrutini"] = {
		Rarity = 300,
		RarityType = "Secret",
		CashPerSecond = 8500,
		Type = "None",
        Timer = 30,
	},
	["Espresso Signora"] = {
		Rarity = 200,
		RarityType = "Secret",
		CashPerSecond = 8880,
		Type = "None",
        Timer = 30,
	},
	["Tigroligre Frutonni"] = {
		Rarity = 100,
		RarityType = "God",
		CashPerSecond = 10000,
		Type = "None",
        Timer = 30,
	},
	Pakrahmatmamat = {
		Rarity = 80,
		RarityType = "God",
		CashPerSecond = 12000,
		Type = "None",
        Timer = 30,
	},
	Pakrahmatmatina = {
		Rarity = 60,
		RarityType = "God",
		CashPerSecond = 15000,
		Type = "None",
        Timer = 30,
	},
	["Chicleteira Bicicleteira"] = {
		Rarity = 40,
		RarityType = "God",
		CashPerSecond = 20000,
		Type = "None",
        Timer = 30,
	},
	["Cachorrito Melonito"] = {
		Rarity = 20,
		RarityType = "God",
		CashPerSecond = 35000,
		Type = "None",
        Timer = 30,
	},
	["Noo My Examen"] = {
		Rarity = 17,
		RarityType = "God",
		CashPerSecond = 43000,
		Type = "None",
        Timer = 30,
	},
	["Yess My Examen"] = {
		Rarity = 15,
		RarityType = "God",
		CashPerSecond = 47000,
		Type = "None",
        Timer = 30,
	},
	["Tric Trac Barabum"] = {
		Rarity = 0,
		RarityType = "Epic",
		CashPerSecond = 225,
		Type = "None",
        Timer = 30,
		Craft = true,
	},
	["Lionel Cactuseli"] = {
		Rarity = 0,
		RarityType = "Legendary",
		CashPerSecond = 1200,
		Type = "None",
        Timer = 30,
		Craft = true,
	},
	["Tirilikalika Tirilikalako"] = {
		Rarity = 0,
		RarityType = "Legendary",
		CashPerSecond = 1250,
		Type = "None",
        Timer = 30,
		Craft = true,
	},
	["Ganganzelli Trulala"] = {
		Rarity = 0,
		RarityType = "Mythic",
		CashPerSecond = 3500,
		Type = "None",
        Timer = 30,
		Craft = true,
	},
	Tralaledon = {
		Rarity = 0,
		RarityType = "Mythic",
		CashPerSecond = 3600,
		Type = "Water",
        Timer = 30,
		Craft = true,
	},
	["La Grande Combinasion"] = {
		Rarity = 0,
		RarityType = "Secret",
		CashPerSecond = 9200,
		Type = "None",
        Timer = 30,
		Craft = true,
	},
	["Triplito Tralaleritos"] = {
		Rarity = 0,
		RarityType = "Secret",
		CashPerSecond = 9500,
		Type = "Water",
        Timer = 30,
		Craft = true,
	},
	["Chicleteirina Bicicleteirina"] = {
		Rarity = 0,
		RarityType = "God",
		CashPerSecond = 25000,
		Type = "Water",
        Timer = 30,
		Craft = true,
	},
	["Chillin Chili"] = {
		Rarity = 0,
		RarityType = "God",
		CashPerSecond = 30000,
		Type = "None",
        Timer = 30,
		Craft = true,
	},
	["Swag Soda"] = {
		Rarity = 0,
		RarityType = "God",
		CashPerSecond = 40000,
		Type = "None",
        Timer = 30,
		Craft = true,
	},
	["W Or L"] = {
		Rarity = 0,
		RarityType = "God",
		CashPerSecond = 45000,
		Type = "None",
        Timer = 30,
		Craft = true,
	},
	["Banana Dancana"] = {
		Rarity = 12,
		RarityType = "OG",
		CashPerSecond = 50000,
		Type = "None",
        Timer = 30,
	},
	["Illuminato Triangolo"] = {
		Rarity = 10,
		RarityType = "OG",
		CashPerSecond = 60000,
		Type = "None",
        Timer = 30,
	},
	["Nyannini Cattalini"] = {
		Rarity = 8,
		RarityType = "OG",
		CashPerSecond = 75000,
		Type = "None",
        Timer = 30,
	},
	["Bananini Kittini"] = {
		Rarity = 5,
		RarityType = "OG",
		CashPerSecond = 100000,
		Type = "None",
        Timer = 30,
	},
	["Smurfo Gatto"] = {
		Rarity = 2,
		RarityType = "OG",
		CashPerSecond = 150000,
		Type = "None",
        Timer = 30,
	},
}